server:
  port: 8080

#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

#spring:
#  main:
#    allow-circular-references: true

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui/index.html